/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame */

#ifndef _Included_collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame
#define _Included_collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame_close
  (JNIEnv *, jclass);

/*
 * Class:     collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_collect_xyd_net_cn_xinyidaicollect_mp3lame_SimpleLame_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
